Add `__attribute__((used))` to library functions
Now that we're using the `-O2` flag, Clang may be removing some of our
functions due to the fact that they're not themselves used in our libc;
however, this behavior appears to be non-deterministic:

1. During the PR tests, the build and tests all succeeded:
   https://github.com/mbrukman/c-stdlib/pull/4/checks?check_run_id=2588271677

2. However, after the PR was merged into `main`, the same test failed:
   https://github.com/mbrukman/c-stdlib/runs/2588277889?check_suite_focus=true

   ```
   FAILED: tests/complex_test_3_8
   ld tests/complex_test_3_8.o lib/libc.a -o tests/complex_test_3_8
   ld: warning: cannot find entry symbol _start; defaulting to 0000000000401000
   ld: tests/complex_test_3_8.o: in function `main':
   complex_test.c:(.text+0x12): undefined reference to `creal'
   ld: complex_test.c:(.text+0x2c): undefined reference to `cimag'
   ```

It's unclear whether the non-determinism is coming from GitHub's proprietary
environment, Ninja, Clang, or something else, so let's add explicit annotations
that these functions should not be removed despite lack of explicit references
from the library itself.